# -*- coding: utf-8 -*-
"""DA Practise .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5w6PYspv7BYVyG5DqIpJ5jp1PyOwXVw
"""

import pandas as pd
df = pd.read_csv("/content/EDA_Ecommerce_Practice_Dataset.csv")

print(df.head(2))
print(df.info())
print(df.describe())
print(df.columns)
#Null values
print(df.isna())
print(df.isna().sum())
df["City"] = df[["City"]].fillna("Unknown")
print(df)
df["Payment_Method"] = df[["Payment_Method"]].fillna("Unknown")
print(df)
df["Age"] = df[["Age"]].fillna(df["Age"].mean())
print(df)
df["Discount"] = df[["Discount"]].fillna(df["Discount"].mean())
df["Rating"] = df[["Rating"]].fillna(df["Rating"].mean())
print(df)
print(df.isna().sum())
#Duplicates
print(df.duplicated().sum())
df = df.drop_duplicates()
print(df)

#cahnge order_date to date_time
df["Order_Date "] = pd.to_datetime(df["Order_Date"])
print(df)
df["Month"] =df["Order_Date "].dt.month_name()
print(df)
df["Year"] =df["Order_Date "].dt.year
print(df)
df["Hour"] =df["Order_Date "].dt.time
print(df)

import pandas as pd
import numpy as np
df = pd.read_csv("/content/Hospital_EDA_Practice_Dataset.csv")
#Viweing Data
print(df.head(5))
print(df.tail(5))
print(df.shape)
print(df.info())
print(df.describe())
print(df.columns)
print(df.dtypes)
print(df.nunique)
#Missing Values
print(df.isna())
print(df.isna().sum())
df["City"] = df["City"].fillna("Unknow")
print(df)
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

df["Payment_Method"] = df["Payment_Method"].fillna("Unknow")
print(df)
df["Diagnosis"] = df["Diagnosis"].fillna("Unknow")
print(df)
df["Insurance_Provider"] = df["Insurance_Provider"].fillna("Unknow")
print(df)
df["Treatment_Cost"] = df["Treatment_Cost"].fillna(df["Treatment_Cost"].mean())
print(df)
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(0)
print(df)
print(df.isna().sum())
#Duplicates
print(df.duplicated().sum())
df = df.drop_duplicates()
print(df)
#Categorical Anlaysis
#Categorical Analysis ├── unique()├── nunique()├── value_counts()└── percentage distribution
df["Gender"].unique()

df["City"].unique()
#Now we are changng this city that should be unique
x =df["City"].astype(str)
print(x)
df["City"]= df["City"].str.title()
print(df["City"])
df["City"] = df["City"].str.strip()
df["City"].unique()
df["Payment_Method"].unique()
df["Discharge_Status"].unique()
df["Insurance_Provider"].unique()


#Numerical Analysis
x=df["Treatment_Cost"].mean()
print(x)
y=df["Treatment_Cost"].sum()
print(y)
z=df["Treatment_Cost"].median()
print(z)
#Ages
print(df["Age"].max())
print(df["Age"].min())
print(df["Age"].sum())
#Heart_Rate
print(df["Heart_Rate"].max())
print(df["Length_of_Stay"].sum())
print(df["Treatment_Cost"].count())
# Outliers
Q1=df["Treatment_Cost"].quantile(0.25)
Q3=df["Treatment_Cost"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["Treatment_Cost"] < lower_bound) |
    (df["Treatment_Cost"] > upper_bound)
]

print(outliers)
print(len(outliers))

# Date & Time├── Year├── Month├── Day├── Day_Name├── Hour└── Quarter
#Date and Time



df["Visit_Date"] = pd.to_datetime(df["Visit_Date"])
print(df["Visit_Date"].dtype)

df["Visit_Year"] = pd.to_datetime(df["Visit_Date"]).dt.year
print(df)

df["Visit_Month"] = pd.to_datetime(df["Visit_Date"]).dt.month_name()
print(df)

df["Day"] = df["Visit_Date"].dt.day
print(df)
df["Day_Name"] = df["Visit_Date"].dt.day_name()
print(df)



df["Hour"] = df["Visit_Date"].dt.hour
print(df)
df["Quarter"] = df["Visit_Date"].dt.quarter
print(df)


#8. Feature Engineering├── Gross Amount ├── Discount Amount └── Profit Margin
df["Cost_Per_Day"] = df["Treatment_Cost"] / df["Length_of_Stay"]
print(df)

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 18, 40, 60, 100],
    labels=["Child", "Young Adult", "Middle Age", "Senior"]
)
print(df)

df["Stay_Category"] = pd.cut(
    df["Length_of_Stay"],
    bins=[0, 3, 7, 30, float("inf")],
    labels=["Short", "Medium", "Long", "Very Long"]
)
print(df)

df["Cost_Per_Age"] = df["Treatment_Cost"] / df["Age"]
print(df)

#Filtering:Conditions

#Q1. Find all patients whose Age is greater than 60.
df["Age_Greater"] = df["Age"] > 60
print(df)


#Q2. Find all patients whose Treatment_Cost is greater than ₹50,000.
df["Treatment"] = df["Treatment_Cost"] > 50000
print(df)


#Q3. Find all patients whose Length_of_Stay is greater than 7 days.
print(df["Length_of_Stay"]>7)

#Q4. Find all patients whose Gender is Female.
print(df["Gender"]=="Female")

#Q5. Find all patients whose Department is Cardiology.
print(df["Department"]== "Cardiology")

#Q6. Find all patients whose Satisfaction_Score is less than 3.
print(df["Satisfaction_Score"]<3)

#Q1. Find the total Treatment_Cost and average Treatment_Cost for each Department.
print(df.head())
print(df.groupby('Department')['Treatment_Cost'].sum())
print(df.groupby('Department')['Treatment_Cost'].median())

#Q2. Find the number of patients and average Age for each Gender.
print(df.groupby('Gender')['Patient_ID'].count())

print(df.groupby('Gender')['Age'].mean())

#Q3. Find the total Treatment_Cost, average Length_of_Stay, and maximum Treatment_Cost for each Admission_Type.
print(df.groupby('Admission_Type')['Treatment_Cost'].sum())
print(df.groupby('Admission_Type')['Length_of_Stay'].mean())
print(df.groupby('Admission_Type')['Treatment_Cost'].max())
#Q4. Find the number of patients in each City and the total Treatment_Cost for each city.
print(df.groupby('City')['Patient_ID'].count())
print(df.groupby('City')['Treatment_Cost'].sum())
#Q5. Find the minimum, maximum, average, and total Treatment_Cost for each Department.

print(df.groupby('Department')['Treatment_Cost'].min())
print(df.groupby('Department')['Treatment_Cost'].max())
print(df.groupby('Department')['Treatment_Cost'].sum())
#Q6. Find the average Heart_Rate and average Satisfaction_Score for each Department.
print(df.groupby('Department')['Heart_Rate'].mean())
print(df.groupby('Department')['Satisfaction_Score'].mean())

#Q7. Find the number of patients, total Treatment_Cost, and average Treatment_Cost for each Insurance_Provider.
print(df.groupby('Insurance_Provider')['Patient_ID'].count())
print(df.groupby('Insurance_Provider')['Treatment_Cost'].sum())
print(df.groupby('Insurance_Provider')['Treatment_Cost'].mean())

#Q8. Find the total Length_of_Stay and average Length_of_Stay for each Diagnosis.
print(df.groupby('Diagnosis')['Length_of_Stay'].sum())
print(df.groupby('Diagnosis')['Length_of_Stay'].mean())

#Q9. Find the number of patients and average Treatment_Cost for each combination of Department and Gender.

print(df.groupby(['Department','Gender']).agg(Patient_count = ("Patient_ID","count"),
                                              Average_Treatment_Cost=("Treatment_Cost","mean")))

#11. Sorting ├── sort_values() ├── nlargest() └── nsmallest()

#Sort the entire dataset by Treatment_Cost in ascending order.
print(df.sort_values("Treatment_Cost"))

#12.Sort the entire dataset by Treatment_Cost in descending order.
print(df.sort_values('Treatment_Cost',ascending=False))

#13.Sort patients by Age from youngest to oldest.
df.sort_values('Age')
#14.Sort the dataset by Length_of_Stay from highest to lowest
df.sort_values('Length_of_Stay')

print(df.sort_values("Treatment_Cost"))
print(df.sort_values('Treatment_Cost',ascending=False))
#Sort patients by Age from oldest to youngest
print(df.sort_values('Age'))
#Sort the dataset by Length_of_Stay from highest to lowest.
df.sort_values('Length_of_Stay',ascending = False)
#

#Find the 5 patients with the highest Treatment_Cost using nlargest()
print(df.nlargest(5,"Treatment_Cost"))
#Find the 5 patients with the lowest Treatment_Cost using nsmallest().
print(df.nsmallest(5,'Treatment_Cost'))
#Find the 10 patients with the highest Length_of_Stay.
print(df.nlargest(10,'Length_of_Stay'))


#Sort the dataset by Department alphabetically and within each Department sort Treatment_Cost from highest to lowest.
df.sort_values(['Department','Treatment_Cost'],ascending=False)

#Find all patients whose Length_of_Stay is less than or equal to 0.
df[df["Length_of_Stay"]<0]

#Find all patients whose Age is negative.
#df[df["Age"]<0.0]
#Find all patients whose Heart_Rate is below 40 or above 200.
df[df["Heart_Rate"]>40]
df[df["Heart_Rate"]>200]

#Find all patients whose Length_of_Stay is less than or equal to 0.
df[df["Length_of_Stay"]<0]
print(df.head())

#

name = "Python is  easy"
print(name)
words = name.split()
print(words)

rev = words[::-1]
s=" ".join(rev)
print(s)

name = "Hello Pyhton Love you"
words = "".join(reversed(name))
print(words)



