# -*- coding: utf-8 -*-
"""MatplotLib_Practise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySlP_LnkFIKTc1XyZ5sUekLGqGmSAg0l
"""

#Introduction
#Matplot Lib:It is a python lib used to create customize and dispaly data visulizations and graphs
#It is widely used in DA,DS,ML and EDA
#importing:import matplotlib.pyplot as plt
#pyplot:provides functions for creating and customizing charts
#for ex:sales[1000,2000,3000,4000,5000]
#For no alone ,it is diff to quickly identify the pattern
#A visulaization can help to identify :1.Highest values 2.Lowest values 3.trends 4 outilers
#simple of matplotlb:
import matplotlib.pyplot as plt
sales = [10,20,30,40,50]
months = ['Jan','Feb','Mar','Apr','May']
plt.plot(months,sales,marker="o")
plt.show()
#Easy flow:RawData--clean data -Matplotlib-visulaization-pattern idefications - insights - decision making
#why do Data Anlystics use matlpotlib:
# A data analyst works with large amounts of numerical and categorical data.Matplotlib helps convert
#that data into visulaization so that trends,comparsions,distrubtions,relationship and outliers can identifies easily



#What matplotlib create:
"""
1.Comparision:1.Bar 2.Horziontal bar 3.Grouped bar 4.Stacked Bar
2.Trends:1.Line,2.Multiple Line,3.Area 4.Stacked Area 5.Step plot 6.stack plot
3.Distribution:1.Histogram 2.Boxplot 3.Vilonplot
4.Relationship:1.Scatter 2.Heaxabin
5.Composition:1.pie 2.Donut 3.Stacked plot 4.Stacked bar
6.Statical/Analytical:Box plot 2.Violn plot 3.Error plot 4.Stem Plot
7.Matrix/Surface:Heatmap 2.Contor 3.Filled contor
8.3D Plots:3D line 2.3D scatter 3.3D bar 4.3D surface 5.3D wireframe 6.3D contor

what type of business questions will ask?
Comparision:1.Bar 2.Horziontal bar 3.Grouped bar 4.Stacked Bar
1.Compare Categories: Bar chart
2.Compare categories with long names:Horziontal Bar chart
3.Compare 2 values for each categories:Grouped Bar chart
4.Show compostition acorrs categories:stacked bar

2.Trends:1.Line,2.Multiple Line,3.Area 4.Stacked Area 5.Step plot 6.stack plot
1.Show trends over time : line chart
2.compare  Multiple trends : Multiple line
3.show trends + Magnitude:Area

3.3.Distribution:1.Histogram 2.Boxplot 3.Vilonplot
 1.Show numerical distrbution:Histogram

 2.Find outliers:Boxplot
 3.compare distibution and denstiy:Vilon


4.Relationship:1.Scatter 2.Heaxabin
 1.Find relationship between numerical variable:Scatter

5.Composition:1.pie 2.Donut 3.Stacked plot 4.Stacked bar 5.step plot
1.Show % contribution:pie
2.Show % contribution + KPI:Donut
3.Show changing composition over time:stack plot
4.show step wise :step plot

7.Matrix/Surface:Heatmap 2.Contor 3.Filled contor
1.show values in a grid:Heatmap style
2.Show mathamtic surface:Contor

8.Show numerical dimension:3D

------------Baisc Matplot Lib structure--------------
import matplotlib.pyplot as plt
#pyplot:it is a module in matplotlib that provides collections function for creating and customizing charts
#
fig=plt.figure()#It overall container holds one or more plots #enitre canvas

plt.plot(x,y,marker="o",line_style="-",label="Sales") #Provides Data
plt.title("My chart") #Create Tile
plt.Xlabel("X Axis") #Labels
plt.Ylabel("Y Axis") #labels
plt.legend()is identified in multiple  data series dispalyed in chart
plt.grid()#it can easier to read values
plt.show() #it disply the chart


"""

#part-1 Comparision:Comparison in Matplotlib means representing data visually so we can easily
#see how different values or groups differ from each other
#Easy memory:Compare two or more things
#comaprision:1.Bar 2.Hoziontal 3.Grouped Bar 4.Stacked Bar
#bar: A bar chart is used to Comapre numerical values across different categories
#Ex:A comapny wants which products want sales highest then we use bar
"""Products =["Laptop","Mobile","Tablet","Watch"]
sales=[120,180,90,110]
plt.figure(figsize=(8,5))
plt.bar(Products,sales)
plt.title("Product Sales")
plt.xlabel("Product")
plt.ylabel("Sales")
#Horiontal:It displays categories vertically and numericals in Horziontal
Products =["Laptop","Mobile","Tablet","Watch"]
sales=[120,180,90,110]
plt.figure(figsize=(8,5))
plt.barh(Products,sales)
plt.title("Product Sales")
plt.xlabel("Product")
plt.ylabel("Sales")"""

#Grouped Bar chart:A grouped bar chart is used to comapre a Multiple numerical values same categories
import numpy as np
Products =["Laptop","Mobile","Tablet","Watch"]
sales=[120,180,90,110]
profit=[30,50,20,25]
x=np.arange(len(Products)) #len(products)=1,2,3,4
width=0.35 #size of bar
plt.bar(x-width/2,sales,width,label='sales') #1-0.35/2=0.17
plt.bar(x+width/2,profit,width,label='profit')#1+0.35/2=-.01.75 it will get side by side
plt.xticks(x,Products)#it display the Products in x axis like Laptop","Mobile","Tablet","Watch
plt.title("Sales VS Profit")
plt.xlabel("Product")
plt.ylabel("Amount")
plt.legend() #it shows a data series
plt.show()

#Stacked Bar chart:A stack bar chart will places a Multiple values on top of each otherwith in the same bar
Products =["Laptop","Mobile","Tablet","Watch"]
sales=[120,180,90,110]
online =[100,150,77,100]
wholesale=[30,40,20,50]

plt.bar(Products,sales,label='Sales')
plt.bar(Products,online,bottom=wholesale,label='online')
plt.bar(Products,wholesale,bottom=sales,label='wholesale')
plt.title("Sales by Product and Channel")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.legend() #it shows a data series
plt.show()

#Compare the total Sales for each Product.
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/matplotlib_clean_practice_dataset.csv')
print(df.head(5))
#1.Compare the total Sales for each Product
x=df['Product']
y=df['Sales']
plt.bar(x,y)
plt.title('Total Sales in Each Product')
plt.xlabel('Products')
plt.ylabel('Sales')
plt.show()

import matplotlib.pyplot as plt



#2.Create a horizontal bar chart to show Salary for each employee.
x=df['Department']
y=df['Salary']
plt.barh(x,y)
plt.title('Department wise Salary')
plt.xlabel('Salary')
plt.ylabel('Department')
plt.show()

#3.Create a grouped bar chart to show Sales and Profit for each row
import numpy as np

#Products=df['Product']
sales=df['Sales']
Profit=df['Profit']
x=np.arange(len(sales))
width=0.55
plt.figure(figsize=(10,5))
plt.bar(x-width/2,sales,width,label='Sales')
plt.bar(x+width/2,Profit,width,label='Profit')
#plt.xticks(x,Sales)
plt.title('Sales Vs Profit')
plt.xlabel('Products')
plt.ylabel('Amount')
plt.show()

#4.Create a stacked bar chart using Sales and Profit for each row.
s=df['Product']
x=df['Sales']
y=df['Profit']
plt.bar(s,x,label='Sales')
plt.bar(s,y,bottom=x,label='Profit')
plt.title('Sales Vs Profit')
plt.xlabel('Product')
plt.ylabel('Amount')
plt.show()

#Trends:It understand how value changes overtime or in an ordered sequence
#1.Line,Mulitple line,Area Chart,stacked Area chart,Step plot,Stack Plot
#line:It is chart that conects data points with lines to show how value changes
#It commonly used to for trends overtime
#1.Increase trends,Descresing Trends 3.Changes over time 4.peaks and drops
import matplotlib.pyplot as plt
months=["Jan","Feb","Mar","Apr","May"]
sales=[100,200,300,400,500]
plt.figure(figsize=(4,5))
plt.plot(months,sales,marker='o')
plt.title('Month Sales')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.show()
#line chart:it shows trends


#Multiple Line chart:2 or more line in same chart
#it shows a multiple trends
months=['Jan','Feb','Mar','Apr','May']
sales=[100,200,300,400,500]
profit=[10,20,30,40,50]
plt.plot(months,sales,marker='o',label='sales')
plt.plot(months,profit,marker='o',label='profit')
plt.title('Sales Vs Profit')
plt.xlabel('months')
plt.ylabel('Amount')
plt.legend()
plt.show()

#Area chart:It is simallar line chart but,the area below the filled with color.it shows how a value changes overtime also give a visula sense
#of the size (magnitude_ of the value)
#we use:1.it shows trends 2.show magintude of the value 3.highlight increase and descrease 4.understange change overtime
months=['jan','Feb','Mar','Apr','may']
sales=[100,200,300,400,500]
plt.fill_between(months,sales,color='yellow')
plt.title('Monthly Sales')
plt.xlabel('month')
plt.ylabel('sales')
plt.show()
#simple:Area chart:trends+Filled Area
#Stacked Area Chart:It displays multiple area stacked on top of each other
#Trends,Total magintude,Contribution of diff catergories
months=['jan','Feb','Mar','Apr','may','jun']
laptop=[40,50,60,70,80,90]
mobile=[30,40,50,60,70,80]
plt.stackplot(months,laptop,mobile,labels=['laptop','mobile'])
plt.title('Laptop and Mobile Sales')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.legend()
plt.show()
#Stacked Area:Trends+compostion

#step Plot:It shows data on stpes that changes in steps ranther than continuously
#it used to when value remain constant for a period and than suddenly changes
#no of orders 2,Stock level 3.price changes 4.Step based measurment
months=['jan','Feb','Mar','Apr','may']
orders=[20,30,45,45,60]
plt.step(months,orders,marker='o')
plt.title('Monthly orders')
plt.xlabel('Months')
plt.ylabel('Orders')
plt.show()
#Stack Plot:A stcak plot is a chart that displays multiple categories on stacked area,show how eacn catergores cntributes to total over time
#We use Stack Plot:See the total value overtime,Understand contributuon each categories
months=['jan','Feb','Mar','Apr','may','jun']
laptop=[40,50,60,70,80,90]
mobile=[30,40,50,60,70,80]
plt.stackplot(months,laptop,mobile,labels=['laptop','mobile'])
plt.title('Laptop and Mobile Sales')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.show()

#

#Create a line chart showing Sales over Date.
print (df)
x=df['Date']
y=df['Sales']
plt.figure(figsize=(5,4))
plt.plot(x,y,marker='o')
plt.title('Date VS Sales')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.show()
#Create a multiple-line chart showing Sales and Profit over Date.
Date=df['Date']
Sales=df['Sales']
Profit=df['Profit']
plt.plot(Date,Sales,marker='o',label='Sales')
plt.plot(Date,Profit,marker='o',label='Profit')
plt.title('Sales VS Profit')
plt.legend()
plt.show()

#Create an area chart showing Sales over Date.
Date=df['Date']
Sales=df['Sales']
plt.fill_between(Date,Sales,label=['Date','Sales'])
plt.title('Date VS Sales')
plt.xlabel('Date')
plt.ylabel('Sales')




#Create a stack plot showing Sales and Profit over Date.
Date=df['Date']
Sales=df['Sales']
Profit=df['Profit']
plt.stackplot(Date,Sales,Profit,labels=['Sales','Profit'])
plt.title('Sales Vs Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.legend()
plt.show()

#Distribution:How the data values are been spread or arranged
#example:10,20,30,40,50 Where are most of the marks?,Are the values close together or spread out?Are there very high or very low values?
#Is the data balanced or skewed?
#Histogrm,BoxPlot,Violn Plot
#Histogram:It is a chart used to show the distribution of numerical data
#Simple:it shows How the numerical values are distributed across ranges
#why:We use histogram to understand where most values are concntracted,How values are spread which range most obseravation
#For ex:[45,50,55,60,65,70,80,85,90,95,100]
#Few students:40 -50,some studes are 50-60 group students 60-70 many students 70-90
#these hstogram shows a group visuallay
#Commons uses:students marks ,Customer age,Salary range,order amount,products price
import matplotlib.pyplot as plt
marks=[30,35,40,45,50,55,60,60,65,70,75,75,80,85,90,95]
plt.hist(marks,bins=6)#bins means it divide data into 5 groups at ranges
plt.title('Distribution of Student Marks')
plt.xlabel('Marks')
plt.ylabel('No of studensts')
plt.show()
#Box Plot:It is a chart used to show the distribution,spread,meadian,quartiles and outliers
#Salary ranges,Customer Spending,Student Marks,Delivery time,products prices
#we use this box plot Find median(middle value),understad the spread(how far the values are)
#See the Quertile (25% and 75%),Identify outliers(usually highe or low)#compare multipe groups easily
marks=[45,50,52,55,60,62,65,68,70,72,75,80,85,90,95,150]
plt.boxplot(marks,vert=True)#vert means vertically
plt.title('Student Marks')
plt.ylabel('Marks')
plt.show()
#outliers:It is a value that usually far from the rest of the data
#Vilon Plot:It is chart shows how data is disrtibuted.It comnines a box plot(meadian,quartiles) with a density plot.
#Violns:shows the distribution and shows the shape of the data,

import matplotlib.pyplot as plt
group_a=[45,50,55,60,65,70,75,80]
group_b=[55,60,63,68,70,75,70,82]
group_c=[40,50,60,70,80,85,90,95]
plt.violinplot([group_a,group_b,group_c], showmeans=True,showmedians=True)
plt.title('Marks Distribution Group')
plt.xlabel('Group')
plt.ylabel('Marks')
plt.xticks([1,2,3],['A','B','C'])
plt.show()

#Create a histogram showing the distribution of Salary.

Salary=df['Salary']
plt.hist(Salary,bins=10)
plt.title('Salary Disturbuted')
plt.ylabel('Salary')
plt.show()
#Create a histogram showing the distribution of Sales using 10 bins.
sales=df['Sales']
plt.hist(sales,bins=10)
plt.title('Sales Distrubuted')
plt.xlabel('Sales')
plt.show()
#Create a box plot showing the spread of Salary.
Salary=df['Salary']
plt.boxplot(Salary)

plt.title('Salary Spread')
plt.ylabel(Salary)
plt.show()
#Create a violin plot showing the distribution of Sales.
Sales=df['Sales']
plt.violinplot(Sales)
plt.show()

#Relationships:Relationship means how two or more variables are connected to or affect each other
#1.Scatter Plot:It is a chart shows relationships between two numerical varibles using individual points
#simple:It is relationships between two numerical varibles
#for ex:study hours:marks,exp-salary,Age-spending,Aversting-sales
import matplotlib.pyplot as plt
study_hour = [2,3,4,5,6,7,8]
marks=[45,50,60,70,88,90,95]
plt.scatter(study_hour,marks)
plt.title('Study_hours Vs Marks')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.show()

#Multiple Scatter Plot:Multiple realtionships or two or more numerical varibles
#Group1:
hours_a=[2,3,4,5,6]
marks_a=[45,50,55,65,75]
#group2:
hour_b=[2,3,4,5,6]
marks_b=[50,58,65,72,88]
plt.scatter(hours_a,marks_a,label='Class A')
plt.scatter(hour_b,marks_b,label='Class B')
plt.title('Study Hours')
plt.xlabel('Study Hour')
plt.ylabel('Marks')
plt.legend()
plt.show()

#Create a scatter plot showing Experience vs Salary.
Experience=df['Experience']
Salary=df['Salary']
plt.scatter(Experience,Salary)
plt.title('Experience Vs Salary')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.show()
print(df.head(5))
#Create a scatter plot showing Customers vs Sales.
Customers=df['Customers']
Sales=df['Sales']
plt.scatter(Customers,Sales)
plt.title('Customers VS Sales')
plt.xlabel('Customers')
plt.ylabel('Sales')
plt.show()
#Create a scatter plot showing Performance vs Salary.
Performance=df['Performance']
Salary=df['Salary']
plt.scatter(Performance,Salary)
plt.title('Performance Vs Salary')
plt.xlabel('Performance')
plt.ylabel('Salary')
plt.show()
#Create a multiple scatter plot using Experience and Salary for different data groups.
Experience=df['Experience']
Salary=df['Salary']
Experience=df['Experience']
Profit=df['Profit']
plt.scatter(Experience,Salary,label='Salary')
plt.scatter(Experience,Profit,label='Profit')
plt.title('Experience Vs Salary VS Profit')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.legend()
plt.show()

#Composition:It means how a total value is divided into diff parts or categories
#Suppose a company's total sales are ₹1,00,000:
#Laptop → ₹50,000
#Mobile → ₹30,000
#Tablet → ₹20,000
#Here, total sales = ₹1,00,000.
#this is called Composition:Parts of a Whole
#1.pie chat,Donut chart
#1.pie chart:A pie chart is a circular chart used represent the % contribution of diff categories to a whole
#Ex:Students Monthly Expenses:Food:3000,Travel:2000 Shooping:1500 other:1500
#percentage:Category value/total value * 100:3000/8000 * 100 =37.5
#sales:Electronic,Claohting
#Webiste traffic like:Google,Soacil media,other
#Company Expenses:Salaries
import matplotlib.pyplot as plt
expenses=[3000,2000,15000,1500]
categories=['Food','Travel','Shooping','Other']
plt.pie(expenses,labels=categories,autopct='%1.1f%%') #autopct:which used to generate automatic percentage
plt.title('Monthly Expenses')
plt.show()

#Donut Chart:It is a variation of a pie chart that uses a hallow center to show the proporation of categories with in a whole
#it used in Sales composition:online ,offline
#Businnes dash board:Customer status :Active 70% Inactive =50
import matplotlib.pyplot as plt
Sales=[60,40]
Channels=['Online','Offline']
plt.pie(Sales,labels=Channels,autopct='%1.1f%%',wedgeprops={'width': 0.4}) #This controls the thickaness of the donut ring
plt.title('Monthly Expenses')
plt.legend()
plt.show()

#Create a pie chart using Sales and Product.
print(df.head(5))
Sales=df['Sales']
Product=df['Product']
plt.pie(Sales,labels=Product,autopct='%1.1f%%')
plt.title('Sales')
plt.legend()
plt.show()
#Create a donut chart using Orders and Department.
Orders=df['Orders']
Department=df['Department']
plt.pie(Orders,labels=Department,autopct='%1.1f%%',wedgeprops={'width':0.21})
plt.title('Orders')
plt.legend()
plt.show()
#Create a pie chart using Sales and Region
Sales=df['Sales']
Region=df['Region']
plt.pie(Sales,labels=Region,autopct='%1.1f%%')
plt.title('Sales')
plt.legend()
plt.show()



Orders=df['Orders']
Department=df['Department']
plt.pie(Orders,labels=Department,autopct='%1.1f%%',wedgeprops={'width':0.32})
plt.title('Orders')
plt.legend()
plt.show()

#Statistical and Analytical:
#Statistical:It means using data to understand things like:center/avg,spread,variation,Distribution,Uncertanity,ouliers
#Analytical:Find the patterns
#Box plot:Distrubution+Meadian,ouliers and Quarntile
#Vilon Plot:Disrubution+Density
#Steam Plot:Individual value and their Distribution
#error bar:Uncertanity or varation
#Steam plot:It is a Statistical plot displays individual data values using vertical or hozoiontal
#in stemas and markers
#indivual observation,Distrubution values,samll data sets gaps between values
marks=[45,50,55,60,65,70,75]
#usued in Distubution of individual marks,Temp randings,#daily sales #samll data sets
import matplotlib.pyplot as plt
marks=[45,50,55,60,65,70,75]
plt.stem(marks)
plt.title('Student Marks')
plt.xlabel('Student')
plt.ylabel('Marks')
plt.show()

#Create a stem plot using Performance.
print(df.head(5))
Performance=df['Performance']
plt.stem(Performance)
plt.title("Performance")
plt.xlabel("Employees")
plt.ylabel("Performance")
plt.show()


#Create a stem plot using Sales
Sales=df['Sales']
plt.stem(Sales)
plt.title("Sales")
plt.xlabel("Products wise sales")
plt.ylabel("Sales")
plt.show()

#Matrix/Numerical Surface
#matri:rows and columns,surface:plan surface
#Heat Map#Contour Plot #Filled Contour Plot
#Heat Map:It is data visulazation that uses color intensity to represent numercial values in a matrix or grid
#Uses:Sales Anlaysis:Rows:Products Columns:MOnths Values:sales
#Customer AnalysisRows:Customer segment 2.Coulmns:Product Categories 3.Values:Purchase Count
import matplotlib.pyplot as plt
import numpy as np
data = np.array([[10,15,20],[15,25,30],[20,30,40]])
plt.imshow(data)
plt.title("Heat map")
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

plt.imshow(data)

for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        plt.text(j, i, data[i, j],
                 ha='center',
                 va='center')

plt.colorbar()
plt.title("Heatmap")
plt.show()

#Contour Plot:It is represent in 3D numerical surface using lines on a 2-D
#A contour plot uses line to conncect points having the same numerical value
#It shows where the values are the same using lines
#Geograph,Weather,Engineering
#Z=x^2+y^2
import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(-5,5,100)
y=np.linspace(-5,5,100)
x, y = np.meshgrid(x, y)
z=x**2+y**2
plt.contour(x,y,z)
plt.colorbar()
plt.title('Contour Bar')
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

#Create a heatmap using the numerical columns.
import matplotlib.pyplot as plt
import numpy as np
print(df.head(5))
data = np.array([[10,15,20],[15,25,30],[20,30,40]])
plt.imshow(data)

#Create a contour plot using Experience, Performance, and Salary.
x=df['Experience']
y=df['Performance']
z=df['Salary']
x, y = np.meshgrid(x, y)
z=x**50+y**50

plt.contour(x,y,z)
plt.contour(x,y,z)
plt.colorbar()


data = df.select_dtypes(include='number')

plt.imshow(data, aspect='auto')
plt.colorbar()

plt.title('Numerical Columns Heatmap')
plt.xlabel('Numerical Columns')
plt.ylabel('Rows')

plt.show()

#Dta Set
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.linspace(50, 100, 100)

X, Y = np.meshgrid(x, y)

Z = X**2 + Y**2

plt.contour(X, Y, Z)
plt.colorbar()

plt.title('Contour Plot')
plt.xlabel('Experience')
plt.ylabel('Performance')


plt.show()

#Sea Born Fundmetals:
#Sea born:It is a pyhton libarary used to create attractive and statistical data visulaization easily:
#Sea born bulit om top of matplotlib
#python-pandles-hanles data-seb born-vizualtion and analyze data-matplotlib-provides the underyling plotting system
#Examples
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
data = {
    'Experience': [1, 2, 3, 5, 8],
    'Salary': [30, 45, 60, 90, 120]  # Added a 5th value to prevent errors
}

# Creating the DataFrame
df = pd.DataFrame(data)
print(df)
sns.scatterplot(df,x='Experience',y='Salary')
plt.show()
#Why do we use seaborn
#1.Easier code:Many statistical charts require less than Matplotlib
#2.Better deafult apperance:The charts generally more polished without much customization
#Works with directly with Pandas
#Excellent for Statical visulaization:Sea born has charts specifically useful for analysis:
#Very useful for EDa:Explority Data Analysis
#The Difference Sea born vs matplotlib
#Matplolib:General visulization libarary #Seaborn:Statical visulazation libarary
#More manual control                      Easier for Analysis
#More customization                       Better Statistical features
#works with arrays/data                works very naturally with Df
#Lower-level plotting control            Higher level analytical plots

#Baic structure:
"""sns.chart_fuction(
    data =df,
    x='column'
    y='column'
    hue='Dept_name'#group the data by another column
)"""
#For Exaplme:
sns.scatterplot(data=df,x='Experience',y='Salary')#which chart,which data ser,x=experience,y='salary
plt.show()

#Understanding:

#Bulit data sets
df=sns.load_dataset('diamonds')
print(df.head())
#Comparasion and category
#How are different catergories different from each other?
#Bar plot:Comapre a numerical value while across categories
#Count Plot:Count the obersvations in categories
#hue:divide cateegories into grups
#1.Barplot():Comapre the numerical values across different categories
#I want liek ask question:1.How Does price diff across diamond cuts?
#ex:Cut vs price
sns.barplot(data=df,x='cut',y='price')
plt.title("Diamod price by cut")
plt.xlabel('Cut')
plt.ylabel('Price')
plt.show()

#2.How does price diff acorss colrs?
sns.barplot(data=df,x='color',y='price')
plt.title("Price from Diff colors")
plt.xlabel('color')
plt.ylabel('Price')
plt.show()

#Bar=value comparision

#count_plot:A cout plot shows the number of observation in each catergory.
#think:Count_plot:count
#1.Example:Number of Diamonds by cut?
sns.countplot(
    data=df,
    x='cut'
)
plt.title("Number of Diamonds are been cut")
plt.xlabel('Cut')
plt.ylabel('Number of diamonds')
plt.show()
#Which color have no of diamonds
sns.countplot(data=df,x='color')

plt.title("Number of Diamonds are been color")
plt.xlabel('Color')
plt.ylabel('Number of diamonds ')
plt.show()

#Grouping with hue:Grouped by the data from different
#1.Number of diamonds by cut ,separeate by color
sns.countplot(data=df,x='cut',hue='color')#x-color,hue-Groups inside each category
plt.title("Diamonds Count by cut and color")
plt.xlabel('cut')
plt.ylabel('Number of diamonds ')
plt.show()

#Bar Plot with Hue
#1.Compare price across cuts,seaprate by diamond color
sns.barplot(data=df,x='cut',y='price',hue='color')
plt.title("Number of Diamonds are been cuts across color")
plt.xlabel('cut')
plt.ylabel('price ')
plt.show()

#Relationship:
#Quesion:How are two numerical variables related to each other
#Imp charts are:1.Scatter plot 2.Line plot 3.Regression plot
#1.Scatter Plot:It is display individual data points to show the relationship
#between two numerical varibles.
#Ex:price cart,carat-price,
#why:wheather two varibles are related,2.wherather increase or decrease 3.pateerns 4.clusters 5.possible oultiers
#Ex:cart vs Price


df=sns.load_dataset('diamonds')
print(df.head())
sns.scatterplot(
    data=df,
    x='carat',
    y='price'
)
plt.title('Carat vs Price')
plt.xlabel('Carat')
plt.ylabel('Price')
plt.show()

#2.Scatter plot with hue
#for exaple:Cart vs Price separate by cut
sns.scatterplot(
    data=df,
    x='carat',
    y='price',
    hue='cut'
)
plt.title('Carat vs Price by cut')
plt.xlabel('Carat')
plt.ylabel('Price')
plt.show()

#Depth Vs Price
sns.scatterplot(
    data=df,
    x='depth',
    y='price'
)
plt.title('depth vs Price')
plt.xlabel('depth')
plt.ylabel('Price')
plt.show()

#Line Plot:Connects values with a line to show change or trend
#Why:How does value chnage for another value change
#It is example only we used for time series data
sns.lineplot(
    data=df,
    x='color',
    y='price',
    marker='o'
)
plt.title('Carat vs Price')
plt.xlabel('Carat')
plt.ylabel('Price')
plt.show()

#Regression plot:It combines scatter plot + Regression Line
#What is meant by regeression : It statistical method usded to the relationship bewteen two numerical varibles and
#pridict/estimate one varible from another
#Ex salary :1 year =30,000 2 years = 35000 3 years =40000
#It helps us see the general linerar trend between two numerical varibles
#It investigate whether there apperas to be line relationship bewtten two numerical varibles
#Exaple cart Vs price
sns.regplot(
    data=df,
    x='carat',
    y='price'
)
plt.title('Carat vs Price with Regression Line')
plt.xlabel('Carat')
plt.ylabel('Price')
plt.show() #in this chart we get Individual points and Regressin line
#

from matplotlib import markers
#Distribution:It means the values in a dataset are spread
df = sns.load_dataset('diamonds')
#Histogram:It shows how numerical values are  distrubed acorrd different ranges or bins
#histogram:Count how many values fall into each range
sns.histplot(data = df,x='price',bins=10) #price-numerical column
plt.title('Distribution of Diamond Prices') #divides the price range into 10 itervals
plt.xlabel('Price')
plt.ylabel('Count')
plt.show()
#uses:understanding data distruibution,FInd concentration values ,EDA


#KDE:Kernel Density Estimate
#It creates a smmoth curve that represents the shape of the distribution
sns.kdeplot(data = df,x='price')
plt.title('Price Distrubution')
plt.xlabel('Price')
plt.ylabel('Density')
plt.show()

#uses:Understand the shape of a distribution 2.Finding peaks 3.Comapring distributions #Identifying skewness
#KDE = Smooth distribution curve

#Histogrma + KDE
sns.histplot(
    data = df,
    x = 'price',
    bins = 20,
    kde = True

)
plt.title("Price Distribution")
plt.xlabel("Price")
plt.ylabel("Count")
plt.show()

#ECDF Plot
#ECDF = Empirical Cumulative Distribution Function
#ECDF shows the Percentage/proportion of observations that are less than or eqaul to a particular value
sns.ecdfplot(data=df,x='price')
plt.title('ECDF of Diamond Prices')
plt.xlabel('Price')
plt.ylabel('Proportion')
plt.show()

#Suppose the curve reaches 0.50 at $2000
#That means 50% of the diamonds have a price less than or equal to 2000
#Rember Cumulative percentage of value

#Box plot:
sns.boxplot(data = df,y='price')
plt.title('Price Distrbution')
plt.ylabel('Price')
plt.show()

#Violn Plot
#Box Plot + KDE disrtibution shape
sns.violinplot(
    data = df,
    x='cut',
    y='price'
)
plt.title('Price Distribution by Cut')
plt.show()

#One Line memory
# Histogrm:How many :Count values in ranges
# KDE : what shape:smmot distribution shape
# Histogram + KDE : count+distribution shape
# ECDF : Cumulative proportion
# Box plot : Spread + meadian + ouliers
# Violin Plot : Spread  + density shape

# Statistical Distribution and Categorical Analysis
# How spread out is my date?
# Are there outliers
# How does the distribution  differ between categories
#For Ex:How is the price distributed across different diamond cuts?
#Box plot:A box plot summarizes the distribution of numerical data and helps us see the median,spread,and potential ouliers
import seaborn as sns
import matplotlib.pyplot as plt
sns.boxplot(
    data = df,
    x='cut',
    y='price'
)  # cut = Categories price = numerical data
plt.title('Price Distributed by Cut')
plt.xlabel('Cut')
plt.ylabel('Price')
plt.show()

#uses:Finding ouliers,Comparing distributions,Understanding median ,Understanding spread, COmparing numerical data across categores

#Violn Plot:It shows the distribution shape of numerical data and also provides summary information similar to a box plot
#Box Plot + KDE disrtibution shape
sns.violinplot(
    data = df,
    x='cut',
    y='price'
)
plt.title('Price Distribution by Cut')
plt.show()

#Strip plot:A strip plot displays individual data points for each category
sns.stripplot(
    data = df,
    x='cut',
    y='price',

)
plt.title('Individual Diamonds Prices by cut')
plt.xlabel('Cut')
plt.ylabel('Price')
plt.show()

#here Each dot indivdual observations
#Box plot:Give me a Summary,Strip plot:Show me actual individual points
#Where do we use:Seeing individual observations 2,Understanig how values are distrbuted inside categories
#spreading unsual obsevations
#strip -> indivaula plot

#Swarm Plot:A swarm plot also shows inidvidual observations,but it tries to arrange the points so they overlap less
#Beacuse of this the data points will show cleary
sns.swarmplot(
    data = df,
    x='cut',
    y='price'

)
plt.title('Indiviudal Diamonds prices by cut')

plt.xlabel('Cut')
plt.ylabel('Price')
plt.show()

#Adavnced EDA
#EDA means Exploratory Data Anlysis
#EDA means charts to understand multiple varibles,relationships,corrleations,and category-based
#summaries
#Heatmap,Pair Plot,Joint Plot,Pivot Table + Heatmap
#Heat map:A heat map represents numerical values using diff levels of visual intensity.
#In DA one of most common uses is corelations heatmap
#Why do we use it?
#To qucikly undestand 1.Which numerical variales are related 2.Postive/Neagitve relationships
#3.Strong/week cooreltions 4.Relationships between many numerical variables at once
print(df.head(5))
#Example:
coor = df[['carat','depth','table','price','x','y','z']] #it create a coorelation matrix
sns.heatmap(
    coor,
    annot = True
)
plt.title(
    "Correlation Heatmap" #then it turns visual heat map
)

#Pair plot:It A pair plot shows relationships between mulitple numerical variables at the same time
#Insted of creating separate scatter plot manually,Seaborn create a grid of plots
#why:Explore many relationships,Find possible correlations ,Identify patterns,Find potential outliers Pefrom initial EDa
sns.pairplot(
    df[['carat','depth','table','price']]
)

#You can also divide the obseravtions into categories
sns.pairplot(
    df[['carat','depth','table','price']],
    hue = 'cut'
)
plt.show() #Now relationship are separated by cut

#Joint plot:A joints plot shows the relationships between two numerical variables along with their individual distributions
#When you want to study two variables deeply
#For eample:Does carrot have a relationship with price?
sns.jointplot(
    data = df,
    x='carat',
    y='price'
)
plt.show()
#Center : relationship between carat and price
#top/side:Distribution of the individual variables

print(df.head())
#heat map+ pivot table:
#pivot table:A pivot tables summarizes data based on categories
#For example:suppose we want:Average diamond price for each cut nad color
import pandas as pd
pivot = pd.pivot_table(
    df,
    values='price',
    index='cut',
    columns='color',
    aggfunc='mean'
)
print(pivot)

#Then we can visualize it:
sns.heatmap(
    pivot,
    annot = True,
)
plt.title('Avaerage Diamond Price by Cut and color')
plt.show()
#uses:Comparing categories,Business summarises,Department * Gender,Reggion Product,Product * Month